version: 2

models:
  - name: stg_telegram_messages
    description: "Staging model for Telegram messages"
    columns:
      - name: message_id
        description: "Unique message ID"
        tests:
          - unique
          - not_null
